#ifndef keytransform_h
#define keytransform_h

// ScanCode - PhysicalKey - Key mapping (the virtual key is mapped as in a standard QWERTY keyboard)
// https://github.com/chromium/chromium/blob/main/ui/events/keycodes/dom/dom_code_data.inc
// This list has the same order as the PhysicalKey enum.
AvnPhysicalKey getAvnPhysicalKeyForCode(int keyCode) {
    int avnPhysicalKey;
    switch (keyCode) {
        case 0x32: return AvnPhysicalKeyBackquote;
        case 0x2A: return AvnPhysicalKeyBackslash;
        case 0x21: return AvnPhysicalKeyBracketLeft;
        case 0x1E: return AvnPhysicalKeyBracketRight;
        case 0x2B: return AvnPhysicalKeyComma;
        case 0x1D: return AvnPhysicalKeyDigit0;
        case 0x12: return AvnPhysicalKeyDigit1;
        case 0x13: return AvnPhysicalKeyDigit2;
        case 0x14: return AvnPhysicalKeyDigit3;
        case 0x15: return AvnPhysicalKeyDigit4;
        case 0x17: return AvnPhysicalKeyDigit5;
        case 0x16: return AvnPhysicalKeyDigit6;
        case 0x1A: return AvnPhysicalKeyDigit7;
        case 0x1C: return AvnPhysicalKeyDigit8;
        case 0x19: return AvnPhysicalKeyDigit9;
        case 0x18: return AvnPhysicalKeyEqual;
        case 0x0A: return AvnPhysicalKeyIntlBackslash;
        case 0x5E: return AvnPhysicalKeyIntlRo;
        case 0x5D: return AvnPhysicalKeyIntlYen;
        case 0x00: return AvnPhysicalKeyA;
        case 0x0B: return AvnPhysicalKeyB;
        case 0x08: return AvnPhysicalKeyC;
        case 0x02: return AvnPhysicalKeyD;
        case 0x0E: return AvnPhysicalKeyE;
        case 0x03: return AvnPhysicalKeyF;
        case 0x05: return AvnPhysicalKeyG;
        case 0x04: return AvnPhysicalKeyH;
        case 0x22: return AvnPhysicalKeyI;
        case 0x26: return AvnPhysicalKeyJ;
        case 0x28: return AvnPhysicalKeyK;
        case 0x25: return AvnPhysicalKeyL;
        case 0x2E: return AvnPhysicalKeyM;
        case 0x2D: return AvnPhysicalKeyN;
        case 0x1F: return AvnPhysicalKeyO;
        case 0x23: return AvnPhysicalKeyP;
        case 0x0C: return AvnPhysicalKeyQ;
        case 0x0F: return AvnPhysicalKeyR;
        case 0x01: return AvnPhysicalKeyS;
        case 0x11: return AvnPhysicalKeyT;
        case 0x20: return AvnPhysicalKeyU;
        case 0x09: return AvnPhysicalKeyV;
        case 0x0D: return AvnPhysicalKeyW;
        case 0x07: return AvnPhysicalKeyX;
        case 0x10: return AvnPhysicalKeyY;
        case 0x06: return AvnPhysicalKeyZ;
        case 0x1B: return AvnPhysicalKeyMinus;
        case 0x2F: return AvnPhysicalKeyPeriod;
        case 0x27: return AvnPhysicalKeyQuote;
        case 0x29: return AvnPhysicalKeySemicolon;
        case 0x2C: return AvnPhysicalKeySlash;
        case 0x3A: return AvnPhysicalKeyAltLeft;
        case 0x3D: return AvnPhysicalKeyAltRight;
        case 0x33: return AvnPhysicalKeyBackspace;
        case 0x39: return AvnPhysicalKeyCapsLock;
        case 0x6E: return AvnPhysicalKeyContextMenu;
        case 0x3B: return AvnPhysicalKeyControlLeft;
        case 0x3E: return AvnPhysicalKeyControlRight;
        case 0x24: return AvnPhysicalKeyEnter;
        case 0x37: return AvnPhysicalKeyMetaLeft;
        case 0x36: return AvnPhysicalKeyMetaRight;
        case 0x38: return AvnPhysicalKeyShiftLeft;
        case 0x3C: return AvnPhysicalKeyShiftRight;
        case 0x31: return AvnPhysicalKeySpace;
        case 0x30: return AvnPhysicalKeyTab;
        case 0x68: return AvnPhysicalKeyLang1;
        case 0x66: return AvnPhysicalKeyLang2;
        case 0x75: return AvnPhysicalKeyDelete;
        case 0x77: return AvnPhysicalKeyEnd;
        case 0x73: return AvnPhysicalKeyHome;
        case 0x72: return AvnPhysicalKeyInsert;
        case 0x79: return AvnPhysicalKeyPageDown;
        case 0x74: return AvnPhysicalKeyPageUp;
        case 0x7D: return AvnPhysicalKeyArrowDown;
        case 0x7B: return AvnPhysicalKeyArrowLeft;
        case 0x7C: return AvnPhysicalKeyArrowRight;
        case 0x7E: return AvnPhysicalKeyArrowUp;
        case 0x47: return AvnPhysicalKeyNumLock;
        case 0x52: return AvnPhysicalKeyNumPad0;
        case 0x53: return AvnPhysicalKeyNumPad1;
        case 0x54: return AvnPhysicalKeyNumPad2;
        case 0x55: return AvnPhysicalKeyNumPad3;
        case 0x56: return AvnPhysicalKeyNumPad4;
        case 0x57: return AvnPhysicalKeyNumPad5;
        case 0x58: return AvnPhysicalKeyNumPad6;
        case 0x59: return AvnPhysicalKeyNumPad7;
        case 0x5B: return AvnPhysicalKeyNumPad8;
        case 0x5C: return AvnPhysicalKeyNumPad9;
        case 0x45: return AvnPhysicalKeyNumPadAdd;
        case 0x5F: return AvnPhysicalKeyNumPadComma;
        case 0x41: return AvnPhysicalKeyNumPadDecimal;
        case 0x4B: return AvnPhysicalKeyNumPadDivide;
        case 0x4C: return AvnPhysicalKeyNumPadEnter;
        case 0x51: return AvnPhysicalKeyNumPadEqual;
        case 0x43: return AvnPhysicalKeyNumPadMultiply;
        case 0x4E: return AvnPhysicalKeyNumPadSubtract;
        case 0x35: return AvnPhysicalKeyEscape;
        case 0x7A: return AvnPhysicalKeyF1;
        case 0x78: return AvnPhysicalKeyF2;
        case 0x63: return AvnPhysicalKeyF3;
        case 0x76: return AvnPhysicalKeyF4;
        case 0x60: return AvnPhysicalKeyF5;
        case 0x61: return AvnPhysicalKeyF6;
        case 0x62: return AvnPhysicalKeyF7;
        case 0x64: return AvnPhysicalKeyF8;
        case 0x65: return AvnPhysicalKeyF9;
        case 0x6D: return AvnPhysicalKeyF10;
        case 0x67: return AvnPhysicalKeyF11;
        case 0x6F: return AvnPhysicalKeyF12;
        case 0x69: return AvnPhysicalKeyF13;
        case 0x6B: return AvnPhysicalKeyF14;
        case 0x71: return AvnPhysicalKeyF15;
        case 0x6A: return AvnPhysicalKeyF16;
        case 0x40: return AvnPhysicalKeyF17;
        case 0x4F: return AvnPhysicalKeyF18;
        case 0x50: return AvnPhysicalKeyF19;
        case 0x5A: return AvnPhysicalKeyF20;
        case 0x49: return AvnPhysicalKeyAudioVolumeDown;
        case 0x4A: return AvnPhysicalKeyAudioVolumeMute;
        case 0x48: return AvnPhysicalKeyAudioVolumeUp;
        default: return AvnPhysicalKeyNone;
    }
};

#endif
