name: Nightly

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  release_nightly:
    uses: AvaloniaUI/build-common/.github/workflows/release-library.yml@main
    with:
      artifact_name: avalonia
      artifact_glob: Avalonia.Controls.WebView.*.nupkg
      push_nightly: true
    secrets:
      checkout_token: ${{ secrets.SUBMODULE_TOKEN }}
      nightly_api_key: ${{secrets.NIGHTLY_FEED_API_KEY}}
