name: Release

on:
  workflow_dispatch:
    inputs:
      create_release:
          description: 'Create GitHub Release'
          required: true
          type: boolean
          default: true

jobs:

  release-for-avalonia:
    uses: AvaloniaUI/build-common/.github/workflows/library-cicd.yml@main
    with:
      runs_on: windows-latest
      install_workloads: "android ios"
      dotnet_sdk: 10.0.103
      artifact_glob: Avalonia.Controls.WebView.*.nupkg
      artifact_name: Avalonia.Controls.WebView
      validate_release_branch: true
      create_github_release: ${{inputs.create_release}}
      push_package: false
    secrets:
      checkout_token: ${{secrets.SUBMODULE_TOKEN}}

  release-for-xpf:
    uses: AvaloniaUI/build-common/.github/workflows/library-cicd.yml@main
    with:
      runs_on: windows-latest        
      install_workloads: "android ios"
      dotnet_sdk: 10.0.103
      artifact_glob: Avalonia.Xpf.Controls.WebView.*.nupkg
      artifact_name: Avalonia.Xpf.Controls.WebView
      validate_release_branch: true
      push_package: false
    secrets:
      checkout_token: ${{secrets.SUBMODULE_TOKEN}}

